### ISSUE TITLE
[Suggestion] use servant collection number as id

### ISSUE THREAD

**Issue by narumi147** [FGOSim/Material#4]
Till now, the servant id was assigned according the author's adding order, it is highly messed up. skipped some id because of beasts, wrong order for those servants released at same time.

So why not use the collection number is id? for compatibility, you can keep the ids that already used. but for future servant, give the correct id.

The last servant Kashin Koji is "374" (should be 380). Hope the next servant is No.381

**Comment by rewoso** [comment]
内容を誤解しているかもしれませんが回答します。

現在保持しているID（Serverdb[xxx].id）は、サイト上での管理IDとしての番号を設定しており、サイト上には基本的に育成できるサーヴァントのみを表示対象としている為、ゲームの内部IDとは一致しません。
また、IDの変更は出来ません。現在サイトを利用頂いている全ユーザーに再度データの登録をしていただく必要が発生する為です。

例えば、ゲーム内IDを別途保持する（Serverdb[xxx].gameid）という事は可能ですが、現状サイトには必要がない為、対応する予定はないです。

この提案によって解決したい問題を教えてください。

[English]
I may be misunderstanding the content, but I will answer.

The currently held ID (Serverdb[xxx].id) is set as a management ID number on the site, and basically only servants that can be trained are displayed on the site, so the game does not match the internal ID of
Also, the ID cannot be changed. This is because all users who are currently using the site will need to register their data again.

For example, it is possible to store the in-game ID separately (Serverdb[xxx].gameid), but there is no plan to support it because it is not necessary for the current site.

Tell us what problem you want this proposal to solve.
